# Generated by Django 5.2.12 on 2026-03-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_filme_diretor_filme_genero_filme_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
